namespace: "adorjan87"
name: "oracle"
version: "1.0.3"
readme: "README.md"
authors:
    - "Adorjan Terjeki"
#dependencies:
#    "other_namespace.collection1": ">=1.0.0"
license:
    - "GPL-2.0-or-later"
tags:
    - oracle19
    - install
    - collection
#repository: "https://www.github.com/my_org/my_collection"
